import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import { FathomAnalytics } from "./fathom";
import { TwitterPixelPageView } from "./twitter-pixel";

const siteName = "OpenClaw DFW";
const title = "OpenClaw DFW — Your AI Employee, Placed & Managed";
const description =
  "I place, secure, and manage your AI executive assistant — like a staffing agency for AI. In-person in Dallas/Fort Worth, remote nationwide.";
const url = "https://openclawdfw.com";

export const metadata: Metadata = {
  title,
  description,
  keywords: [
    "OpenClaw setup",
    "OpenClaw deployment",
    "AI assistant Dallas",
    "AI assistant Fort Worth",
    "AI executive assistant DFW",
    "AI employee",
    "managed AI service",
    "OpenClaw security hardening",
    "Dallas Fort Worth",
    "DFW AI",
    "AI staffing",
    "AI automation DFW",
  ],
  metadataBase: new URL(url),
  alternates: {
    canonical: url,
  },
  openGraph: {
    title,
    description,
    url,
    siteName,
    locale: "en_US",
    type: "website",
    // og:image is auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
    creator: "@cgenco",
    // twitter:image is auto-generated by opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
  },
  other: {
    "theme-color": "#ff4d4d",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Twitter/X Pixel */}
        <Script id="twitter-pixel" strategy="afterInteractive">
          {`
            !function(e,t,n,s,u,a){e.twq||(s=e.twq=function(){s.exe?s.exe.apply(s,arguments):s.queue.push(arguments);},s.version='1.1',s.queue=[],u=t.createElement(n),u.async=!0,u.src='https://static.ads-twitter.com/uwt.js',a=t.getElementsByTagName(n)[0],a.parentNode.insertBefore(u,a))}(window,document,'script');
            twq('config','r4pmu');
          `}
        </Script>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-PPY2WJG6WZ"
          strategy="afterInteractive"
        />
        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-PPY2WJG6WZ');
          `}
        </Script>
        {/* Microsoft/Bing UET Tag */}
        <Script id="microsoft-uet" strategy="afterInteractive">
          {`
            (function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"187235232",enableAutoSpaTracking:true};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.bing.com/bat.js","uetq");
          `}
        </Script>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": ["Service", "LocalBusiness"],
              name: siteName,
              url,
              description:
                "White-glove AI employee placement and management for founders and business owners in Dallas/Fort Worth. In-person or remote.",
              provider: {
                "@type": "Person",
                name: "Christian Genco",
                url: "https://christian.gen.co",
                sameAs: ["https://x.com/cgenco"],
              },
              areaServed: [
                { "@type": "City", name: "Dallas" },
                { "@type": "City", name: "Fort Worth" },
                {
                  "@type": "Place",
                  name: "Dallas–Fort Worth metroplex",
                },
              ],
              contactPoint: {
                "@type": "ContactPoint",
                contactType: "customer service",
                url: `${url}/book`,
              },
              priceRange: "$$$",
            }),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "FAQPage",
              mainEntity: [
                {
                  "@type": "Question",
                  name: "What is OpenClaw?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "An open-source AI assistant that can triage email, schedule meetings, draft replies, and automate workflows across your tools — running on your own hardware like a new employee.",
                  },
                },
                {
                  "@type": "Question",
                  name: "What's included in a Placement?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "In-person installation and security hardening, email and calendar integration, custom workflow buildout, integration with your business software, training, and a 1-week follow-up. For DFW clients, we come to your office.",
                  },
                },
                {
                  "@type": "Question",
                  name: "How long does setup take?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "Most placements are completed in a single day. You go live the same day, and we follow up within a week to fine-tune everything.",
                  },
                },
                {
                  "@type": "Question",
                  name: "Do you offer ongoing support?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "Yes. Agent Management is our ongoing retainer where I serve as the manager of your AI employee — handling monitoring, security updates, performance reviews, and training to make sure it keeps getting better.",
                  },
                },
                {
                  "@type": "Question",
                  name: "Is it secure?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "Security is our top priority. OpenClaw runs on hardware you control — not a SaaS black box. We onboard it like a new employee: read-only access first, approval flows for sensitive actions, its own credentials. You can literally unplug it.",
                  },
                },
              ],
            }),
          }}
        />
      </head>
      <body className="text-gray-100 antialiased">
        <FathomAnalytics />
        <TwitterPixelPageView />
        {children}
      </body>
    </html>
  );
}
